require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/towns", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Town. As you add validations to Town, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Town.create! valid_attributes
      get towns_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      town = Town.create! valid_attributes
      get town_url(town)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_town_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      town = Town.create! valid_attributes
      get edit_town_url(town)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Town" do
        expect {
          post towns_url, params: { town: valid_attributes }
        }.to change(Town, :count).by(1)
      end

      it "redirects to the created town" do
        post towns_url, params: { town: valid_attributes }
        expect(response).to redirect_to(town_url(Town.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Town" do
        expect {
          post towns_url, params: { town: invalid_attributes }
        }.to change(Town, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post towns_url, params: { town: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested town" do
        town = Town.create! valid_attributes
        patch town_url(town), params: { town: new_attributes }
        town.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the town" do
        town = Town.create! valid_attributes
        patch town_url(town), params: { town: new_attributes }
        town.reload
        expect(response).to redirect_to(town_url(town))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        town = Town.create! valid_attributes
        patch town_url(town), params: { town: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested town" do
      town = Town.create! valid_attributes
      expect {
        delete town_url(town)
      }.to change(Town, :count).by(-1)
    end

    it "redirects to the towns list" do
      town = Town.create! valid_attributes
      delete town_url(town)
      expect(response).to redirect_to(towns_url)
    end
  end
end
